//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class PosRotMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/PosRot";
        public override string RosMessageName => k_RosMessageName;

        public float pos_x;
        public float pos_y;
        public float pos_z;
        public float rot_x;
        public float rot_y;
        public float rot_z;
        public float rot_w;
        public float angle;
        public float poss_x;
        public float poss_y;
        public float poss_z;
        public float rott_x;
        public float rott_y;
        public float rott_z;
        public float rott_w;
        public float anglee;

        public PosRotMsg()
        {
            this.pos_x = 0.0f;
            this.pos_y = 0.0f;
            this.pos_z = 0.0f;
            this.rot_x = 0.0f;
            this.rot_y = 0.0f;
            this.rot_z = 0.0f;
            this.rot_w = 0.0f;
            this.angle = 0.0f;
            this.poss_x = 0.0f;
            this.poss_y = 0.0f;
            this.poss_z = 0.0f;
            this.rott_x = 0.0f;
            this.rott_y = 0.0f;
            this.rott_z = 0.0f;
            this.rott_w = 0.0f;
            this.anglee = 0.0f;
        }

        public PosRotMsg(float pos_x, float pos_y, float pos_z, float rot_x, float rot_y, float rot_z, float rot_w, float angle, float poss_x, float poss_y, float poss_z, float rott_x, float rott_y, float rott_z, float rott_w, float anglee)
        {
            this.pos_x = pos_x;
            this.pos_y = pos_y;
            this.pos_z = pos_z;
            this.rot_x = rot_x;
            this.rot_y = rot_y;
            this.rot_z = rot_z;
            this.rot_w = rot_w;
            this.angle = angle;
            this.poss_x = poss_x;
            this.poss_y = poss_y;
            this.poss_z = poss_z;
            this.rott_x = rott_x;
            this.rott_y = rott_y;
            this.rott_z = rott_z;
            this.rott_w = rott_w;
            this.anglee = anglee;
        }

        public static PosRotMsg Deserialize(MessageDeserializer deserializer) => new PosRotMsg(deserializer);

        private PosRotMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos_x);
            deserializer.Read(out this.pos_y);
            deserializer.Read(out this.pos_z);
            deserializer.Read(out this.rot_x);
            deserializer.Read(out this.rot_y);
            deserializer.Read(out this.rot_z);
            deserializer.Read(out this.rot_w);
            deserializer.Read(out this.angle);
            deserializer.Read(out this.poss_x);
            deserializer.Read(out this.poss_y);
            deserializer.Read(out this.poss_z);
            deserializer.Read(out this.rott_x);
            deserializer.Read(out this.rott_y);
            deserializer.Read(out this.rott_z);
            deserializer.Read(out this.rott_w);
            deserializer.Read(out this.anglee);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos_x);
            serializer.Write(this.pos_y);
            serializer.Write(this.pos_z);
            serializer.Write(this.rot_x);
            serializer.Write(this.rot_y);
            serializer.Write(this.rot_z);
            serializer.Write(this.rot_w);
            serializer.Write(this.angle);
            serializer.Write(this.poss_x);
            serializer.Write(this.poss_y);
            serializer.Write(this.poss_z);
            serializer.Write(this.rott_x);
            serializer.Write(this.rott_y);
            serializer.Write(this.rott_z);
            serializer.Write(this.rott_w);
            serializer.Write(this.anglee);
        }

        public override string ToString()
        {
            return "PosRotMsg: " +
            "\npos_x: " + pos_x.ToString() +
            "\npos_y: " + pos_y.ToString() +
            "\npos_z: " + pos_z.ToString() +
            "\nrot_x: " + rot_x.ToString() +
            "\nrot_y: " + rot_y.ToString() +
            "\nrot_z: " + rot_z.ToString() +
            "\nrot_w: " + rot_w.ToString() +
            "\nangle: " + angle.ToString() +
            "\nposs_x: " + poss_x.ToString() +
            "\nposs_y: " + poss_y.ToString() +
            "\nposs_z: " + poss_z.ToString() +
            "\nrott_x: " + rott_x.ToString() +
            "\nrott_y: " + rott_y.ToString() +
            "\nrott_z: " + rott_z.ToString() +
            "\nrott_w: " + rott_w.ToString() +
            "\nanglee: " + anglee.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
